### ISSUE TITLE
Generate Factories for the Repository classes

### ISSUE THREAD

**Issue by rossmitchell** [edmondscommerce/doctrine-static-meta#21]

**Comment by rossmitchell** [comment]
`<?php

namespace EdmondsCommerce\Vault\Model\Repositories;

use Doctrine\ORM\EntityManagerInterface;
use EdmondsCommerce\Vault\Entities\Client;
use EdmondsCommerce\Vault\Entity\Repositories\ClientRepository;

class Factory
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * Factory constructor.
     *
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function getClientRepository(): ClientRepository
    {
        $metaData = $this->entityManager->getClassMetadata(Client::class);

        return new ClientRepository($this->entityManager, $metaData);
    }
}`

**Comment by edmondscommerce** [comment]
This has now been completed
