### ISSUE TITLE
Consider removing return types from field traits

### ISSUE THREAD

**Issue by rossmitchell** [edmondscommerce/doctrine-static-meta#25]
Currently they trigger errors in PHPStan if using fluid setters

**Comment by rossmitchell** [comment]
Using fluid setter with the generate classes such as this

**Comment by edmondscommerce** [comment]
looks like if we remove the return types from the interface and switch the other return types to `self` then we get a good compromise

**Comment by edmondscommerce** [comment]
This needs properly testing to find the best compromise

Looks like what we really were hoping for was https://en.wikipedia.org/wiki/Covariant_return_type

But what we have with PHP is invariant return types - https://wiki.php.net/rfc/return_types#examples

We can remove return types altogether (not good) or find some kind of compromise
